

services:
   mysql:
    container_name: mysql
    command: --innodb-use-native-aio=0
    image: mysql:5.7
    restart: always
    networks:
      - nodenet
    volumes:
      - volumedb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    tty: true

   node:
    build: 
       context: .
       dockerfile: dockerfile.node
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 80s node index.js
    image: guijs02/node-cycle
    networks:
      - nodenet
    ports:
      - "4000:4000"
    volumes:
      - ./src:/var/www/node
    depends_on:
      - mysql
    restart: unless-stopped
      
      
   nginx:
    build: 
       context: .
       dockerfile: dockerfile.ng
    container_name: nginx
    image: guijs02/nginx-cycle
    ports:
      - 8080:80
    networks:
      - nodenet
    depends_on:
      - node

networks:
  nodenet:
    driver: bridge
    name: nodenet

volumes:
  volumedb:
  volumenode:




